CREATE TABLE users_details(
user_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_Email VARCHAR(150) NOT NULL UNIQUE,
user_PW VARCHAR(225) NOT NULL,
user_surname VARCHAR(150) NOT NULL,
user_other_names VARCHAR(150) NOT NULL,
gender VARCHAR(255),
user_birth_day INT NOT NULL,
user_birth_month INT NOT NULL,
user_birth_year INT NOT NULL,
company_of_employ VARCHAR(150) NOT NULL,
dept_of_employ VARCHAR(150) NOT NULL,
job_title VARCHAR(225) NOT NULL,
pre_comp_of_employ VARCHAR(225) NOT NULL,
user_country_of_res VARCHAR(225) NOT NULL,
user_phone_number VARCHAR(225) NOT NULL,
hi_inst_attended VARCHAR(225) NOT NULL,
other_inst_attended VARCHAR(225) NOT NULL,
other_qualifn VARCHAR(225) NOT NULL,
tech_interest VARCHAR(225) NOT NULL,
general_interest VARCHAR(225) NOT NULL,
know_how VARCHAR(225) NOT NULL,
bio BLOB NOT NULL,
profile_pix_path VARCHAR(225) NOT NULL,
user_signature_path VARCHAR(225) NOT NULL,
doc_access_status VARCHAR(225) NOT NULL,
verification_status VARCHAR(10) NOT NULL,
act_code VARCHAR(255)
)ENGINE = InnoDB;